sumologic:
  sumologic:
    accessId: dummy
    accessKey: dummy
    endpoint: http://receiver-mock.receiver-mock:3000/terraform/api/

  fluentd:
    metrics:
      autoscaling:
        enabled: true
        maxReplicas: 1000

  kube-prometheus-stack:
    enabled: false

prometheusSpec:
  kubeStateMetrics:
    namespace: kps
  scrapeInterval: "10s"
